### ISSUE TITLE
Playback Jumps when changing albums.

### ISSUE THREAD

**Issue by patchorang** [rttomlinson/spotify-record-player#1]
Sometime when changing an album, the previous album will play for a second before switch to the new album.

**Comment by rttomlinson** [comment]
Thanks for filing the issue, @patchorang. I'll start working on this.

**Comment by patchorang** [comment]
Roger

**Comment by rttomlinson** [comment]
Fixed this by not making the player play on transfer. working on a more robust solution but closing this for now
